### ISSUE TITLE
sound output over bluetooth

### ISSUE THREAD

**Issue by hdavid** [danomatika/PdParty#55]
hi,

thanks for pd party, which is awesome ! for some reason the audio output seems to _not_ work over bluetooth.
i suppose this is linked to the way the audio devices is accessed to reduce the latency. but other applications like Korg Gadget work fine over bluetooth for audio. could you have a look ?

regards

**Comment by danomatika** [comment]
It _does_ work or _doesn't_ work over bluetooth?

**Comment by hdavid** [comment]
edited :) sorry.

**Comment by danomatika** [comment]
In reading some details about iOS & bluetooth audio, it looks like it will work automatically if the receiving device has the same input & output capabilities as what the app is using. By default, PdParty has both sound input & output so it seems like a device with only an output (aka speakers) won't connect automatically since it doesn't have a microphone. To get around this requires a lot of extra code.

**Comment by hdavid** [comment]
interesting. in the meantime i worked on my own app and integrated libPd (amazingly easy ! ) and i get audio out on BT speaker and BT headset. not sure how the iphone "sees" the headset (with or without mic enabled) but it works there (we dont use the libpd audio input). 
thanks for digging on that one. interesting! feel free to close the ticket

**Comment by danomatika** [comment]
Closing for now, although better bluetooth support may come in PdParty 1.3.0.
