### ISSUE TITLE
Only comments are visible.

### ISSUE THREAD

**Issue by clavisound** [danomatika/PdParty#73]
Thank you about the PdParty, it's a long dream come true. Also OSC support. THANK YOU!

To my understanding I have to transfer the pd patches from computer (Linux + pd-0.50-2) to iOS. I did and none of my patches are working, except from comments.

Simple patch uploaded to iOS-12.5.4, only comment is visible.
```
#N canvas 332 249 450 300 10;
#X msg 152 82 2;
#X floatatom 152 45 5 0 0 0 - - -, f 5;
#X text 93 18 clv test patch for PdParty;
#X connect 1 0 0 0;
```
I did the reverse. I downloaded multibeat example from droidpart and opened with PD. Everything ok but two objects are missing

```
s-loader
... couldn't create
 numberbox 64 32 bpm-r bpm 30 300 125
... couldn't create
```

I did something wrong or this is a bug?

Thank you.

**Comment by danomatika** [comment]
GUid without send/recurved are not rendered. Please read the patching section in the PdParty guide.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by clavisound** [comment]
Oh! Excuse me, I made the assumption for drop-in replacement from the introduction. Maybe it’s useful to add this info to the intro.

Thanks an excuse me, I read now, try later :)

**Comment by danomatika** [comment]
GUI emulation requires send/receives for now. This is also true for PdDroidParty, which is why multi beat worked for you.

If we rework the GUI messaging inside the Pd core so it’s generally accessible via libpd, this requirement could change in the future.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com
